# docker-compose.yml
version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=your_secret_key
      - JWT_EXPIRES_IN=24h
      - API_TOKEN=er-api-token
    restart: always