# docker-compose.yml
version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT:-5000}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - API_TOKEN=${API_TOKEN}
    restart: always