name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "PORT=5000" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env

      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d --remove-orphans
